script: "bundle exec rake"
bundler_args: "--without development production"
language: ruby
rvm:
  - 2.2.3
branches:
  only:
    - master
before_script:
  - psql -c 'create database burn-notice_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:test:prepare
