sudo: false
addons:
  postgresql: "9.4"
services:
  - postgresql
language: ruby
script: "bundle exec rake"
bundler_args: "--without development production"
before_script:
  - psql --version
  - psql -c 'create database "burn-notice_test";' -U postgres
  - RAILS_ENV=test bundle exec rake db:test:prepare
