# Use the README file as a reference to customize settings.

Article:
  fields:
    default: title, body, user_id, published_at, tags, content
    form: title, body, user_id, published_at, tags, content
  relationships: 
  application: Application
