# Use the README file as a reference to customize settings.

Article:
  fields:
    default: title, body, user, published_at, tags, headline, content
    form: title, body, user, published_at, tags, headline, content
  relationships: user
  application: Application
