# Use the README file as a reference to customize settings.

Authorization:
  fields:
    default: provider, uid, user_id
    form: provider, uid, user_id
  relationships: 
  application: Application
