# Use the README file as a reference to customize settings.

Notice:
  fields:
    default: data, token, user_id, question, status
    form: data, token, user_id, question, status
  relationships: openings, policy
  application: Application
