development:
  adapter: postgresql
  database: burn-notice_development
  username: postgres
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: burn-notice_test
  username: postgres
  host: localhost
  encoding: utf8
